spring.application.name=SpringAI
server.port=8081

#for multiple AI at once
spring.ai.chat.client.enabled=false


#GEMINI AI CONFIG(Configuring using properties)
spring.ai.openai.api-key=${GEMINI_API_KEY}
# Gemini OpenAI-compatible endpoint
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
# Model
spring.ai.openai.chat.options.model=gemini-3.5-flash






#Local Model implementation

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=codellama:latest
spring.ai.ollama.chat.options.temperature=0.7


#log

logging.level.org.springframework.ai.chat.client.advisor=DEBUG