spring.application.name=SpringAI
server.port=8081

#api key (OpenAI)
spring.ai.openai.api-key=${GEMINI_API_KEY}

# Gemini OpenAI-compatible endpoint
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai

# Model
spring.ai.openai.chat.options.model=gemini-2.5-flash